"""initial schema

Revision ID: ed5721a5fce3
Revises: 
Create Date: 2026-09-11 06:03:31.285356
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ed5721a5fce3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_settings_updated_at'), ['updated_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor', ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_updated_at'), ['updated_at'], unique=False)

    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags'))
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_flags_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_feature_flags_updated_at'), ['updated_at'], unique=False)

    op.create_table('models',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('license', sa.String(length=120), nullable=False),
    sa.Column('size_mb', sa.Integer(), nullable=False),
    sa.Column('vram_mb', sa.Integer(), nullable=False),
    sa.Column('speeds', sa.String(length=64), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('install_path', sa.String(length=512), nullable=False),
    sa.Column('download_url', sa.String(length=512), nullable=False),
    sa.Column('requires_extra', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_models_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_updated_at'), ['updated_at'], unique=False)

    op.create_table('subscriptions',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('monthly_credits', sa.Integer(), nullable=False),
    sa.Column('used_credits', sa.Integer(), nullable=False),
    sa.Column('renews_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_updated_at'), ['updated_at'], unique=False)

    op.create_table('usage',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage')),
    sa.UniqueConstraint('owner_id', 'day', 'metric', name='uq_usage_owner_day_metric')
    )
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_updated_at'), ['updated_at'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_asset_id', sa.String(length=64), nullable=True),
    sa.Column('storage_quota_mb', sa.Integer(), nullable=False),
    sa.Column('storage_used_mb', sa.Float(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)

    op.create_table('avatars',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('avatar_type', sa.String(length=64), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('voice_id', sa.String(length=64), nullable=True),
    sa.Column('reference_asset_id', sa.String(length=64), nullable=True),
    sa.Column('thumbnail_asset_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_avatars_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avatars'))
    )
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avatars_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_avatars_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avatars_updated_at'), ['updated_at'], unique=False)

    op.create_table('projects',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_asset_id', sa.String(length=64), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_is_favorite'), ['is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_updated_at'), ['updated_at'], unique=False)

    op.create_table('prompts',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('enhanced_text', sa.Text(), nullable=False),
    sa.Column('structured', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_prompts_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts'))
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_updated_at'), ['updated_at'], unique=False)

    op.create_table('voices',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('engine', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('accent', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('style', sa.String(length=64), nullable=False),
    sa.Column('emotion', sa.String(length=64), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.Column('sample_asset_id', sa.String(length=64), nullable=True),
    sa.Column('is_cloned', sa.Boolean(), nullable=False),
    sa.Column('consent', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_voices_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voices'))
    )
    with op.batch_alter_table('voices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_voices_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_voices_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voices_updated_at'), ['updated_at'], unique=False)

    op.create_table('workflows',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_job_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_workflows_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows'))
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_updated_at'), ['updated_at'], unique=False)

    op.create_table('assets',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('preview_key', sa.String(length=512), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('parent_asset_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_assets_owner_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_assets_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_is_favorite'), ['is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_assets_owner_kind', ['owner_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_assets_project_kind', ['project_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_updated_at'), ['updated_at'], unique=False)

    op.create_table('characters',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('locks', sa.JSON(), nullable=False),
    sa.Column('reference_asset_ids', sa.JSON(), nullable=False),
    sa.Column('voice_id', sa.String(length=64), nullable=True),
    sa.Column('thumbnail_asset_id', sa.String(length=64), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_characters_owner_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_characters_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters'))
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_characters_project', ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_updated_at'), ['updated_at'], unique=False)

    op.create_table('jobs',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('engine', sa.String(length=120), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('gpu', sa.String(length=120), nullable=True),
    sa.Column('eta_seconds', sa.Float(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_jobs_owner_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jobs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_engine'), ['engine'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_jobs_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_queued_at'), ['queued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_updated_at'), ['updated_at'], unique=False)

    op.create_table('project_versions',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_versions_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_versions'))
    )
    with op.batch_alter_table('project_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_project_versions_project_entity', ['project_id', 'entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_versions_updated_at'), ['updated_at'], unique=False)

    op.create_table('scenes',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('dialogue', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('video_prompt', sa.Text(), nullable=False),
    sa.Column('character_ids', sa.JSON(), nullable=False),
    sa.Column('image_asset_id', sa.String(length=64), nullable=True),
    sa.Column('video_asset_id', sa.String(length=64), nullable=True),
    sa.Column('audio_asset_id', sa.String(length=64), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scenes_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes'))
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenes_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_scenes_project_index', ['project_id', 'index'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenes_updated_at'), ['updated_at'], unique=False)

    op.create_table('generations',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('engine', sa.String(length=120), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_generations_job_id_jobs')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_generations_owner_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_generations_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generations'))
    )
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generations_engine'), ['engine'], unique=False)
        batch_op.create_index(batch_op.f('ix_generations_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generations_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_generations_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_generations_owner_kind', ['owner_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_generations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_generations_updated_at'), ['updated_at'], unique=False)

    op.create_table('shots',
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('camera', sa.String(length=64), nullable=False),
    sa.Column('lens', sa.String(length=32), nullable=False),
    sa.Column('motion', sa.String(length=64), nullable=False),
    sa.Column('lighting', sa.String(length=64), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('transition', sa.String(length=64), nullable=False),
    sa.Column('character_id', sa.String(length=64), nullable=True),
    sa.Column('voice_id', sa.String(length=64), nullable=True),
    sa.Column('dialogue', sa.Text(), nullable=False),
    sa.Column('sfx', sa.String(length=200), nullable=False),
    sa.Column('image_asset_id', sa.String(length=64), nullable=True),
    sa.Column('video_asset_id', sa.String(length=64), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_shots_project_id_projects')),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_shots_scene_id_scenes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shots'))
    )
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index('ix_shots_scene_index', ['scene_id', 'index'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shots_updated_at'))
        batch_op.drop_index('ix_shots_scene_index')
        batch_op.drop_index(batch_op.f('ix_shots_scene_id'))
        batch_op.drop_index(batch_op.f('ix_shots_project_id'))
        batch_op.drop_index(batch_op.f('ix_shots_created_at'))

    op.drop_table('shots')
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_generations_status'))
        batch_op.drop_index(batch_op.f('ix_generations_project_id'))
        batch_op.drop_index('ix_generations_owner_kind')
        batch_op.drop_index(batch_op.f('ix_generations_owner_id'))
        batch_op.drop_index(batch_op.f('ix_generations_kind'))
        batch_op.drop_index(batch_op.f('ix_generations_job_id'))
        batch_op.drop_index(batch_op.f('ix_generations_engine'))
        batch_op.drop_index(batch_op.f('ix_generations_created_at'))

    op.drop_table('generations')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_updated_at'))
        batch_op.drop_index('ix_scenes_project_index')
        batch_op.drop_index(batch_op.f('ix_scenes_project_id'))
        batch_op.drop_index(batch_op.f('ix_scenes_created_at'))

    op.drop_table('scenes')
    with op.batch_alter_table('project_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_versions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_project_versions_project_id'))
        batch_op.drop_index('ix_project_versions_project_entity')
        batch_op.drop_index(batch_op.f('ix_project_versions_created_at'))

    op.drop_table('project_versions')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_type'))
        batch_op.drop_index('ix_jobs_status_priority')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_queued_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))
        batch_op.drop_index('ix_jobs_owner_status')
        batch_op.drop_index(batch_op.f('ix_jobs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_engine'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))

    op.drop_table('jobs')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_updated_at'))
        batch_op.drop_index(batch_op.f('ix_characters_project_id'))
        batch_op.drop_index('ix_characters_project')
        batch_op.drop_index(batch_op.f('ix_characters_owner_id'))
        batch_op.drop_index(batch_op.f('ix_characters_created_at'))

    op.drop_table('characters')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_updated_at'))
        batch_op.drop_index('ix_assets_project_kind')
        batch_op.drop_index(batch_op.f('ix_assets_project_id'))
        batch_op.drop_index('ix_assets_owner_kind')
        batch_op.drop_index(batch_op.f('ix_assets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_assets_kind'))
        batch_op.drop_index(batch_op.f('ix_assets_is_favorite'))
        batch_op.drop_index(batch_op.f('ix_assets_created_at'))
        batch_op.drop_index(batch_op.f('ix_assets_checksum'))

    op.drop_table('assets')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_updated_at'))
        batch_op.drop_index(batch_op.f('ix_workflows_owner_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_created_at'))

    op.drop_table('workflows')
    with op.batch_alter_table('voices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voices_updated_at'))
        batch_op.drop_index(batch_op.f('ix_voices_owner_id'))
        batch_op.drop_index(batch_op.f('ix_voices_language'))
        batch_op.drop_index(batch_op.f('ix_voices_created_at'))

    op.drop_table('voices')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_prompts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_prompts_created_at'))

    op.drop_table('prompts')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_updated_at'))
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))
        batch_op.drop_index(batch_op.f('ix_projects_kind'))
        batch_op.drop_index(batch_op.f('ix_projects_is_favorite'))
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))

    op.drop_table('projects')
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avatars_updated_at'))
        batch_op.drop_index(batch_op.f('ix_avatars_owner_id'))
        batch_op.drop_index(batch_op.f('ix_avatars_created_at'))

    op.drop_table('avatars')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_updated_at'))
        batch_op.drop_index(batch_op.f('ix_usage_owner_id'))
        batch_op.drop_index(batch_op.f('ix_usage_day'))
        batch_op.drop_index(batch_op.f('ix_usage_created_at'))

    op.drop_table('usage')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_owner_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_created_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_updated_at'))
        batch_op.drop_index(batch_op.f('ix_models_status'))
        batch_op.drop_index(batch_op.f('ix_models_key'))
        batch_op.drop_index(batch_op.f('ix_models_family'))
        batch_op.drop_index(batch_op.f('ix_models_created_at'))

    op.drop_table('models')
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flags_updated_at'))
        batch_op.drop_index(batch_op.f('ix_feature_flags_key'))
        batch_op.drop_index(batch_op.f('ix_feature_flags_created_at'))

    op.drop_table('feature_flags')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_actor')

    op.drop_table('audit_logs')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_updated_at'))
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))
        batch_op.drop_index(batch_op.f('ix_app_settings_created_at'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
